on: [pull_request]

jobs:
  update-detect-gpu-benchmarks:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    name: Update benchmarks
    if: ${{github.event.pull_request.user.login == 'dependabot[bot]'}}
    steps:
      - name: create task
        env:
          LINEAR_API_KEY: ${{secrets.LINEAR_API_KEY}}
        id: task
        uses: opera-joakimd/linear-task-action@main
        with:
          team: "action-test"
          pr_name: ${{github.event.pull_request.title}}
      - name: "Setup git"
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: "Update benchmarks"
        shell: bash
        run: |
          cd public
          wget -c https://github.com/pmndrs/detect-gpu/raw/master/benchmarks.tar.gz -O - | tar -xz
          rm -r benchmarks
          mv benchmarks-min benchmarks
      - name: "Push changes"
        uses: EndBug/add-and-commit@v9
        with:
          add: "public/benchmarks/"
          message: "${{steps.task.outputs.task_id}}: Update benchmarks"
          new_branch: ${{github.head_ref}}
          default_author: "github_actions"
          github_token: ${{secrets.GITHUB_TOKEN}}
