on: [pull_request_target]
# add types? opened, reopened, synchronize?

jobs:
  update-detect-gpu-benchmarks:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    name: Update benchmarks
    if: ${{github.event.pull_request.user.login == 'dependabot[bot]'}}
    steps:
      #- name: create task
      #  id: task
      #  uses: opera-joakimd/linear-task-action@main
      #  with:
      #    key: ${{secrets.LINEAR_API_KEY}}
      #    team: "action-test"
      #    pr_name: ${{github.event.pull_request.title}}
      #- name: Setup git
      #  run: |
      #    git init
      #    git config --local user.name github-actions[bot]
      #    git config --local user.email github-actions[bot]@users.noreply.github.com
      #    git remote add origin "https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git"
      #    git fetch
      #    git checkout ${{github.head_ref}}
      #- name: "Update benchmarks"
      #  shell: bash
      #  run: |
      #    cd public
      #    wget -c https://github.com/pmndrs/detect-gpu/raw/master/benchmarks.tar.gz -O - | tar -xz
      #    rm -r benchmarks
      #    mv benchmarks-min benchmarks
      #- name: Commit and squash
      #  run: |
      #    git add .
      #    git commit -m "temp"
      #    git reset --soft $(git log -1 --format=format:%H)~2
      #    git commit -m "${{steps.task.outputs.task_id}}: ${{github.event.pull_request.title}}"
      #    git push -f
      - name: Rename PR
        run: |
          curl --request PATCH \
          --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}} \
          --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
          --header 'content-type: application/json' \
          --data '{"title": "MOCK-12: ${{github.event.pull_request.title}}"}'
      #- name: Rename PR
      #  run: |
      #    curl -L \
      #    -X PATCH \
      #    -H "Accept: application/vnd.github+json" \
      #    -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
      #    -H "X-GitHub-Api-Version: 2022-11-28" \
      #    https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}} \
      #    -d '{"title":"${{steps.task.outputs.task_id}}: ${{github.event.pull_request.title}}"}'
