on: [pull_request_target]

jobs:
  update-detect-gpu-benchmarks:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    name: Update benchmarks
    if: ${{github.event.pull_request.user.login == 'dependabot[bot]'}}
    steps:
      - name: create task
        id: task
        uses: opera-joakimd/linear-task-action@main
        with:
          key: ${{secrets.LINEAR_API_KEY}}
          team: "action-test"
          pr_name: ${{github.event.pull_request.title}}
      - run: echo '${{ toJSON(github) }}'
      - run: |
          git init
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git remote add origin "https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.event.repository.name}}.git"
          git fetch
          git checkout ${{github.head_ref}}
      - name: "Update benchmarks"
        shell: bash
        run: |
          cd public
          wget -c https://github.com/pmndrs/detect-gpu/raw/master/benchmarks.tar.gz -O - | tar -xz
          rm -r benchmarks
          mv benchmarks-min benchmarks
      - run: |
          git add .
          git commit -m "temp"
          git reset --soft $(git log -1 --format=format:%H)~2
          git commit -m "${{steps.task.outputs.task_id}}: ${{github.event.pull_request.title}}"
          git push -f
