on: [pull_request_target]

jobs:
  update-detect-gpu-benchmarks:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    name: Update benchmarks
    if: ${{github.event.pull_request.user.login == 'dependabot[bot]'}}
    steps:
      - name: create task
        id: task
        uses: opera-joakimd/linear-task-action@main
        with:
          key: ${{secrets.LINEAR_API_KEY}}
          team: "action-test"
          pr_name: ${{github.event.pull_request.title}}
      # - name: "Setup git"
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     repository: ${{ github.event.pull_request.head.repo.full_name }}
      #     ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git init
          git config user.name github-actions
          git remote add origin "https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/opera-joakimd/using-updates.git"
          git fetch
          git checkout ${{github.head_ref}}
      - name: "Update benchmarks"
        shell: bash
        run: |
          cd public
          wget -c https://github.com/pmndrs/detect-gpu/raw/master/benchmarks.tar.gz -O - | tar -xz
          rm -r benchmarks
          mv benchmarks-min benchmarks
      - run: |
          git add .
          git commit -m "temp"
          git reset --soft $(git log -1 --format=format:%H)~2
          git commit -m "${{steps.task.outputs.task_id}}: ${{github.event.pull_request.title}}"
          git push -f
      #- name: "Push changes"
      #  uses: EndBug/add-and-commit@v9
      #  with:
      #    add: "public/benchmarks/"
      #    message: "${{steps.task.outputs.task_id}}: Update benchmarks"
      #    new_branch: ${{github.head_ref}}
      #    default_author: "github_actions"
      #    github_token: ${{secrets.GITHUB_TOKEN}}

  #  git reset --shoft HEAD~2

# git commit -m 'new commit message'
